**D1** Which of **these** has dimension \(L^2\)? [Dimension]

[+] Acre [That's right]
[] Mile  [That's just \(L\).]
[] Light year  [A length, not an area.]
[] Foot candle  
[] Foot pound  [This is torque, not area.]

**D2** What is the dimension of energy? [Dimension]

[+] M L\(^2\) / T\(^2\)  [Force times distance]
# comment line
[] m c\(^2\)  [This isn't a dimension, it's a quantity. But it's useful to remind you of what the dimension of energy is. \(c\) has dimension L / T]
[] L\(^2\) T\(^2\) / M 
[] L T M 

**D3** Which planet are we on? [Debugging]

[] Mercury  [Too close to the sun for me!]
[] Venus [Still too hot, although I guess it's due to CO\(_2\)]
[a] Earth [Home, sweet home]
[] Mars [In the movies, maybe]

**D4** How many days in a week? [Debugging]

[] 1 
[] 3 
[] 5 
[a] 7 ["Sabbath" comes from the Hebrew word for "rest," but it's quite close to the word for "seven."]
[] 9

**D5** How many hours in a day? [Debugging]

[] 12
[a] 24
[] 36
[] 48

**Dback1** You are given \(\partial_x\,f(x) \equiv 0\). What is \(f(x)\)? <br>And can I write `x+1` ? And follow that with an equation $$e = mc^2$$ And after that, some lines of code <br><pre>f <- makeFun(x^2 ~ x)</pre>[Basic-Derivatives]

[+] \(f(x) \equiv a\)
[] \(f(x) \equiv a + b x\)
[] \(f(x) \equiv a x + b\)
[] \(f(x) \equiv a + b x^2\)
[] \(f(x) \equiv a x^2 + b\)
[] \(f(x) \equiv a + b x + c x^2\)
[] \(f(x) \equiv a + b x + c x^2 / 2\)
[] \(f(x) \equiv a + 2b  x + c x^2\)
[] \(f(x) \equiv a + 2b x + c x^2/2\)
[] \(f(x) \equiv a x + b x\)
[] \(f(x) \equiv a x^2/2 + b x^2/2\)

**legitnames1** Is `xx` a legitimate name in R? [Day-2-A]

[a] True
[] False

**legitnames2** Is `x_x` a legitimate name in R? [Day-2-A]

[a] True
[] False

**legitnames3** Is `-x` a legitimate name in R? [Day-2-A]

[] True
[a] False [The minus sign are other such symbols are not allowed characters in an R name.]

**legitnames4** Is `3x` a legitimate name in R? [Day-2-A]

[] True
[a] False [Names should start with a letter]

**legitnames5** Is `x3` a legitimate name in R? [Day-2-A]

[a] True [Numbers are OK in names, so long as the first character is a letter]
[] False

**legitnames6** Is `sqrt` a legitimate name in R? [Day-2-A]

[a] True [In fact, it is the name of an oft-used function in R.]
[] False

**legitnames7** Is `x + y` a legitimate name in R? [Day-2-A]

[] True
[a] False [`x + y` is an R expression that uses names, but the expression is not itself a name.]

**legitnames8** Is `3 * x` a legitimate name in R? [Day-2-A]

[] True
[a] False [`*` and <space> are not acceptable characters in a name.]

**legitnames9** Is `xprime` a legitimate name in R? [Day-2-A]

[a] True
[] False

**legitnames10** Is `x prime` a legitimate name in R? [Day-2-A]

[] True
[a] False [A space is not allowed in a name in R.]

**legitnames11** Is `dx` a legitimate name in R? [Day-2-A]

[a] True
[] False

**legitnames12** Is `xx` a legitimate name in R? [Day-2-A]

[a] True
[] False

**legitnames13** Is `dx_f` a legitimate name in R? [Day-2-A]

[a] True
[] False

**assign1** What's wrong with this assignment statement?<br> `x < 4` [2-B]

[] Nothing
[a] It's missing part of the `<-` token.
[]  `x` is an improper name.

**assign2** What's wrong with this assignment statement?<br> `3*x <- 4` [2-B]

[] Nothing [The item to the left of `<-` needs to be a valid name. `3*x` is not.]
[] It should use addition instead of multiplication.
[a] The item to the left of `<-` needs to be a name [`3 * x` is an instruction to multiply 3 times x. It is not a name.]
[] There's no `x` on the right-hand side of the assignment arrow. 

**assign3** What's wrong with this assignment statement?<br> `x -> 3+4` [2-B]

[] Nothing 
[] You can't use addition in an assignment statement. [You can, but it has to be on the right side of the assignment, where you construct the value to be assigned to the name on the left side.]
[a] The assignment has to point toward the **name**, not the *value*

**assign4** We can write something like $$f(x) \equiv x^2$$ in mathematical notation. Is it legit in R to write `f(x) <- x^2` ? [2-B]

[] Yes, it's fine.
[a] `f(x)` is not a valid name in R.
[] Almost. You need to use \(\equiv\) instead of `<-` . [There's no symbol \(\equiv\) on the keyboard or recognized in the R language.]

**arg11** Will this statement work in R? <br>`sin(4)` [3-A]

[a] Yes
[] No

**arg12** Will this statement work in R? <br>`Sin(4)`</br> [3-A]

[] Yes [The built-in R function is `sin()`, not `Sin()`. R treats capital and lower-case letters as completely different, so the name `abby` is utterly distinct from `Abby` or `aBBy`, etc.]
[a] No [It would except for the capital S. R treats capital and lower-case letters as completely different, so the name `abby` is utterly distinct from `Abby` or `aBBy`, etc.]

**arg13** Will this statement work in R to calculate $\sin(4)$ ? <br> `sin[4]` [3-A]

[] Yes [You must always use parentheses, not square braces, to carry the argument to the function.]
[a] No [Only parentheses can be used to hand an argument off to a function.]

**arg14** What is the output from the command `log(-1)` ? [3-A]

[] 0 [Sorry, but $\ln(1) \rightarrow 0$, not $\ln(-1)$.
[] An error message. [A warning is different from an error.]
[] -Inf 
[a] NaN [\(-1\) is outside of the domain of the logarithm function.]

**arg15** What is the output from the command `log(0)` ? [3-A]

[] 0 
[a] -Inf [There's a vertical asymptote involved here, so the programmers who wrote `log()` decided to tell you which direction it goes in.]
[] NaN

**arg16** Which of these phrases is most appropriate for describing what the R command `z <- sin(17)` is doing?  [3-A]

[] Gives a name to a value.
[a] Applies a function to an input to produce an output.
[] Makes a copy of an existing object.
[] The name of an object.
[] It's invalid as a command.

**arg17** Which of these phrases is most appropriate for describing what the R command `sin(17)` is doing?  [3-A]

[] Gives a name to a value.
[a] Applies a function to an input to produce an output.
[] Makes a copy of an existing object.
[] The name of an object.
[] It's invalid as a command.

**arg18** Which of these phrases is most appropriate for describing what the R command `z <- x` is doing?  [3-A]

[] Gives a name to a value.
[] Applies a function to an input to produce an output.
[a] Makes a copy of an existing object.
[] The name of an object.
[] It's invalid as a command.

**arg10** Which of these phrases is most appropriate for describing what the R command `fred` is doing?  [3-A]

[] Gives a name to a value.
[] Applies a function to an input to produce an output.
[] Makes a copy of an existing object.
[a] The name of an object. [When you give the name of an object as a stand-alone command, R prints out the value of that object.]
[] It's invalid as a command.

**arg11** In the statement `pnorm(3, mean=4, sd=6 )`, what is `pnorm`?  [3-A]

[a] The name of the function being applied to the three arguments.
[] A named argument
[] An argument to be used without a name.

**arg12** In the statement `pnorm(3, mean=4, sd=6 )`, what is `mean=4`?  [3-A]

[] The name of the function being applied to the three arguments.
[a] A named argument
[] An argument to be used without a name.

**arg13** In the statement `pnorm(3, mean=4, sd=6 )`, what is `3`?  [3-A]

[] The name of the function being applied to the three arguments.
[] A named argument
[a] An argument to be used without a name.

**arg14** Will the statement `pnorm(x=3, mean=4, sd=6)` give the same result as `pnorm(3, mean=4, sd=6)` ?  [3-A]

[] Yes, same arguments to the same function means the output will be the same. [In general, this is good reasoning. ]
[a] No. The name of the first argument to `pnorm()` is not `x`. [You can't always know what are the names of the arguments to the basic built-in functions. So use them without naming the argument.]

**arg15** Will the statement `pnorm(3, mean=4, sd=6)` give the same result as `pnorm(3, sd=6, mean=4)`?  [3-A]

[a] Yes. [The names for the arguments tell R how each argument should be used in the function.]
[] No. The arguments are different. [When an argument is used with it's name, it can go anywhere in the argument list.]

**arg16** Will the statement `pnorm(3, mean=4, sd=6)` give the same result as `pnorm(3, sd=4, mean=6)`?  [3-A]

[] Yes [Look carefully at the value given to each argument.]
[a] No [In the first statement, the mean is set to 4, while in the second it's set to 6.]

